name: build
on:
  push:
    branches:
      - master

jobs:
  compilejobUbuntu:
    runs-on: ubuntu-latest
    name: Binder_on_Ubuntu
    timeout-minutes: 1320
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: binder:latest
        file: docker/Dockerfile
        build-args: |
          NCPUS=4

  compilejobFedora35:
    runs-on: ubuntu-latest
    name: Binder_on_Fedora35
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compileindocker
      uses: ./.github/workflows/fedora35
    - name: Get the output status
      run: exit ${{ steps.compileindocker.outputs.out }}

  compilejobOSX:
    runs-on: macos-latest
    name: Binder_on_OSX
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compile
      run: ./.github/workflows/osx/entrypoint.sh
    - name: Get the output status
      run: exit ${{ steps.compile.outputs.out }}
