name: build
on:
  push:
    branches:
      - master

jobs:
  compilejobUbuntu:
    runs-on: ubuntu-latest
    name: Binder_on_Ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")

    - name: ccache cache files
      uses: pat-s/always-upload-cache@v3.0.2
      env:
        cache-name: cache-ccache
      with:
        path: ${{ github.workspace }}/docker/cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${ { steps.ccache_cache_timestamp.outputs.timestamp } }
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Build-01
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: docker/Dockerfile
        image: binder
        tags: incremental-01
        build-args: |
          NCPUS=4
        extra-args: |
          -v ${{ github.workspace }}/docker/ccache:/home/root/.config/ccache
          --target incremental-01

    # - name: Build-02
    #   uses: redhat-actions/buildah-build@v2
    #   with:
    #     containerfiles: docker/Dockerfile
    #     image: binder
    #     tags: incremental-02
    #     build-args: |
    #       NCPUS=4
    #     extra-args: |
    #       -v ${{ github.workspace }}/docker/ccache:/home/root/.ccache
    #       --target incremental-02

    - name: Build-03
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: docker/Dockerfile
        image: binder
        tags: final latest
        build-args: |
          NCPUS=4
        extra-args: |
          -v ${{ github.workspace }}/docker/ccache:/home/root/.config/ccache
          --target final

    - name: Build-test
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: docker/Dockerfile
        image: binder
        tags: test
        build-args: |
          NCPUS=4
        extra-args: |
          -v ${{ github.workspace }}/docker/ccache:/home/root/config/.ccache
          --target test

  compilejobFedora35:
    runs-on: ubuntu-latest
    name: Binder_on_Fedora35
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compileindocker
      uses: ./.github/workflows/fedora35
    - name: Get the output status
      run: exit ${{ steps.compileindocker.outputs.out }}

  compilejobOSX:
    runs-on: macos-latest
    name: Binder_on_OSX
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compile
      run: ./.github/workflows/osx/entrypoint.sh
    - name: Get the output status
      run: exit ${{ steps.compile.outputs.out }}
